### ISSUE TITLE
Dynamically add and/or remove outputs to components

### ISSUE THREAD

**Issue by roelvanegmond** [totaljs/flowstreamdesigner#1]
Hi Peter,

As you told us it is currently not possible to dynamic add and/or remove outputs to components. This is something we would like to so to make more dynamic components/configurations possible.

**Comment by petersirka** [comment]
I'll think about it during this weekend. I'll give you feedback.

**Comment by petersirka** [comment]
I have analyzed the FlowStream, and dynamic outputs/inputs aren't possible to support. The reason is simple. Inputs/outputs must be declared in the component, so each instance (from the component) contains a reference to this component. According to it, the FlowStream Designer and FlowStream core generate/validate/verify outputs/inputs. So we don't have any way to manipulate inputs/outputs dynamically because everything comes out from the component declaration.

I know that this is a missing feature, but I don't see any way to implement it right now. I would have to change the core, and it's not an easy thing.

**Comment by roelvanegmond** [comment]
Closed!, Is done.
