### ISSUE TITLE
exports.npm = ["handlebars", "libxmljs2"]; Can not be installed

### ISSUE THREAD

**Issue by AlejandroSotoCastro** [totaljs/flowstreamdesigner#22]
Steps to reproduce

- Create a flow.
- Create a component with the following header:

```

exports.npm = ["handlebars", "libxmljs2"];

exports.make = function (instance, config) {
    const xmljs = require("libxmljs2");

...

```
- Put the component in the flow
- Create a second flow.
- Create the same component there
- Put the component in the flow
- Error in the terminal

**Comment by petersirka** [comment]
@AlejandroSotoCastro this is fixed. The problem is a bit complicated, worker thread can't use same C/C++ compiled Node.js modules in the same process (I don't know why (I must research it)).

- update definitions/modules from <https://github.com/totaljs/flowstream/>

__WorkerThread mode__:
- you need to enable `flowstream_sandbox   : true` <https://github.com/totaljs/flowstream/blob/main/config#L15>
- then the FlowStream will create independent `node_modules` directory for each FlowStream

__ChildProcess/Fork mode__:
- change only `flowstream_worker  : fork` to `fork`

Or disable `flowstream_worker  : false`

Thank you.
